# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank='True', max_length=40)),
                ('user_point', models.IntegerField(blank='True', default=0)),
            ],
        ),
    ]
