# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chutzpah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='user_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='user_point',
            field=models.IntegerField(default=0),
        ),
    ]
