# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181223_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clublist',
            name='ClubMember',
        ),
    ]
